# Odd/Even Sudoku training config

defaults:
  - arch: hrm_v1
  - _self_

hydra:
  output_subdir: null

# Data path (set after preprocessing)
data_path: data/sudoku-odd-even-1k

# Hyperparams - Training
global_batch_size: 768

epochs: 20000
eval_interval: 2000
checkpoint_every_eval: True

lr: 1e-4
lr_min_ratio: 1.0
lr_warmup_steps: 2000

# Optim
beta1: 0.9
beta2: 0.95
weight_decay: 0.1
puzzle_emb_weight_decay: 0.1

# Puzzle embeddings
puzzle_emb_lr: 1e-2


